workflows:
  vs_xode:
    name: VS-Xode

    environment:
      node: 20

    scripts:
      - name: Disable LFS
        script: |
          git lfs install --skip-smudge

      - name: Install dependencies
        script: npm ci

      - name: Compile
        script: npm run compile

    artifacts:
      - out/**
